"use strict";
window.SMC = window.SMC || {};
SMC.k2manual = (function () {
    var api=SMC.api,ui=SMC.ui,batches=[],loaded=false,previewUrl='',editingPaper=-1;
    var DRAFT_KEY='smc_k2_one_row_batch_v1';
    var batch={id:'',teacher:'',subject:'',schoolYear:'',papers:[],dirty:false};
    var QUESTIONS=[
        ['Classroom Cleanliness','My teacher keeps our classroom clean and makes our classroom pleasant.'],
        ['Life-Enhancing Classroom Discipline','My teacher helps me to listen and checks if I understand the lesson well.'],
        ['Life-Enhancing Classroom Discipline','My teacher reminds me to pick up trash and clean my table.'],
        ['Life-Enhancing Classroom Discipline','My teacher comes and leaves the class on time.'],
        ['Life-Enhancing Classroom Discipline','My teacher helps me to be friendly and close to Jesus.'],
        ['Mastery of the Subject Matter','My teacher speaks clearly and explains the lesson at their best.'],
        ['Mastery of the Subject Matter','My teacher gives a short and quick quiz about the lesson explained.'],
        ['Mastery of the Subject Matter','My teacher asks different kinds of questions that I can answer.'],
        ['Mastery of the Subject Matter','My teacher shows colorful pictures and videos on screen that help me better understand the lesson.'],
        ['Mastery of the Subject Matter','My teacher gives very interesting activities that make me listen well.'],
        ['Teaching Personality','My teacher is neat and clean and looks very respectful.'],
        ['Teaching Personality','My teacher is friendly, smiles often, and says kind words to me.'],
        ['Teaching Personality','My teacher is patient and does not get angry often.']
    ];
    function esc(s){return ui&&ui.esc?ui.esc(s==null?'':s):String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
    function toast(m,k){if(ui&&ui.toast)ui.toast(m,k);}
    function errText(e,f){var m=e&&e.message?e.message:f;if(/unknown action/i.test(String(m||'')))return 'The one-row K2 batch backend is not deployed. Replace the backend files, edit the existing Apps Script deployment, choose New version, and deploy.';return m||f;}
    function blankBatch(){return{id:'',teacher:'',subject:'',schoolYear:'',papers:[],dirty:false};}
    function loadDraft(){try{var x=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(x&&Array.isArray(x.papers))batch={id:String(x.id||''),teacher:String(x.teacher||'').toUpperCase(),subject:String(x.subject||'').toUpperCase(),schoolYear:String(x.schoolYear||''),papers:x.papers.map(function(p){p.student=String(p.student||'').toUpperCase();p.gradeLevel=String(p.gradeLevel||'').toUpperCase();return p;}),dirty:!!x.dirty};}catch(e){}}
    function saveDraft(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(batch));}catch(e){}}
    function syncCommon(){var t=document.getElementById('k2Teacher');if(!t)return;batch.teacher=t.value.trim().toUpperCase();batch.subject=document.getElementById('k2Subject').value.trim().toUpperCase();batch.schoolYear=document.getElementById('k2SchoolYear').value.trim();}
    function markDirty(){batch.dirty=true;saveDraft();drawBatch();}
    function scoreValues(){return QUESTIONS.map(function(_,i){var x=document.querySelector('input[name="k2q'+i+'"]:checked');return x?Number(x.value):null;});}
    function avg(a){return a.length?Math.round(a.reduce(function(s,n){return s+n;},0)/a.length*100)/100:null;}
    function calc(scores){var v=scores.filter(function(n){return n>=1&&n<=4;});return{cleanliness:avg(scores.slice(0,1).filter(Boolean)),discipline:avg(scores.slice(1,5).filter(Boolean)),mastery:avg(scores.slice(5,10).filter(Boolean)),personality:avg(scores.slice(10,13).filter(Boolean)),overall:avg(v),answered:v.length};}
    function fmt(v){return v==null?'—':Number(v).toFixed(2);}
    function drawResults(){var h=document.getElementById('k2LiveResults');if(!h)return;var r=calc(scoreValues());h.innerHTML='<div><span>Cleanliness</span><b>'+fmt(r.cleanliness)+'</b></div><div><span>Discipline</span><b>'+fmt(r.discipline)+'</b></div><div><span>Subject Mastery</span><b>'+fmt(r.mastery)+'</b></div><div><span>Personality</span><b>'+fmt(r.personality)+'</b></div><div class="k2-overall"><span>Overall</span><b>'+fmt(r.overall)+'</b><small>'+r.answered+'/13 answered</small></div>';}
    function questionsHtml(){var h='',cat='',open=false;QUESTIONS.forEach(function(q,i){if(q[0]!==cat){if(open)h+='</div>';cat=q[0];open=true;h+='<div class="k2-paper-section"><div class="k2-paper-cat">'+esc(cat)+'</div>';}h+='<div class="k2-paper-row"><div class="k2-paper-question"><span class="k2-bullet">•</span>'+esc(q[1])+'</div><div class="k2-paper-choices">';[4,3,2,1].forEach(function(n){h+='<label><input type="radio" name="k2q'+i+'" value="'+n+'"><span>'+n+'</span></label>';});h+='</div></div>';});if(open)h+='</div>';return h;}
    function pdfModal(){return '<div class="k2-pdf-modal" id="k2PdfModal" hidden><div class="k2-pdf-box"><div class="k2-pdf-head"><b id="k2PdfName">PDF preview</b><div><a id="k2PdfDrive" target="_blank" rel="noopener">Open in Drive</a><button id="k2PdfDownload" type="button">Download PDF</button><button id="k2PdfClose" type="button">×</button></div></div><iframe id="k2PdfFrame" title="Compiled answered papers PDF preview"></iframe><div class="k2-pdf-foot" id="k2PdfFoot"></div></div></div>';}
    function template(){return '<section class="k2-card" id="k2Card"><div class="k2-head"><div><span class="k2-kicker">Paper Evaluation Encoder</span><h3>Kinder–Grade 2 Manual Evaluation</h3><p>Stage all answered papers for one teacher and subject, then save them as one batch record.</p></div><button class="k2-collapse" id="k2Collapse" type="button">Open encoder</button></div><div class="k2-body" id="k2Body" hidden><div class="k2-tabs"><button class="on" data-k2tab="entry">Batch entry</button><button data-k2tab="saved">Saved batches</button></div><div class="k2-panel on" id="k2Panel-entry"><div class="k2-entry-grid"><aside class="k2-entry-side">'+
        '<div class="k2-common"><label>Name of Teacher <small>SURNAME, FIRST NAME</small><input id="k2Teacher" autocomplete="off" placeholder="DELA CRUZ, MARIA"></label><label>Subject <small>Automatically ALL CAPS</small><input id="k2Subject" autocomplete="off" placeholder="MATHEMATICS"></label><label>School Year <small>Numbers only</small><input id="k2SchoolYear" type="text" inputmode="numeric" pattern="[0-9]*" autocomplete="off" placeholder="2026"></label></div><div class="k2-batch" id="k2Batch"></div><div class="k2-paper-chips" id="k2PaperChips"></div><div class="k2-status" id="k2Status"></div></aside><div class="k2-entry-main">'+
        '<div class="k2-paper"><div class="k2-paper-cn"><label>Class No. (optional) <input id="k2ClassNo" type="text" inputmode="numeric" pattern="[0-9]*" autocomplete="off"></label></div><div class="k2-paper-title"><b>STELLA MARIS COLLEGE</b><strong>STUDENT EVALUATION TO CLASSROOM TEACHER</strong><span>(KINDER – GRADE 2)</span></div><div class="k2-paper-fields"><label>Your Name: <input id="k2Student" autocomplete="off"></label><label>Grade Level: <select id="k2GradeLevel"><option value="">Select grade level</option><option value="KINDER">KINDER</option><option value="GRADE 1">GRADE 1</option><option value="GRADE 2">GRADE 2</option></select></label></div><div class="k2-paper-direction"><b>DIRECTION:</b> Select the number that describes the teacher best.</div><div class="k2-paper-legend"><span><b>4</b> ALWAYS</span><span><b>3</b> MOST OF THE TIME</span><span><b>2</b> SOMETIMES</span><span><b>1</b> NEVER</span></div><div id="k2Questions">'+questionsHtml()+'</div><label class="k2-paper-comment"><b>Write something about your teacher.</b><span>My teacher is</span><textarea id="k2Comment" rows="2" maxlength="2000"></textarea></label></div>'+
        '<details class="k2-result-details"><summary>View automatic results for this paper</summary><div class="k2-results" id="k2LiveResults"></div></details><div class="k2-actions"><button class="k2-primary" id="k2AddPaper" type="button">Add paper to batch</button><button id="k2ClearPaper" type="button">Clear paper</button></div></div></div></div>'+
        '<div class="k2-panel" id="k2Panel-saved"><div class="k2-filters"><label>Teacher<input id="k2FilterTeacher" placeholder="All teachers"></label><label>Subject<input id="k2FilterSubject" placeholder="All subjects"></label><label>School year<input id="k2FilterYear" placeholder="All years"></label><button id="k2Filter" type="button">Apply</button></div><div class="k2-list-meta" id="k2ListMeta"></div><div class="k2-table-wrap"><table class="k2-table"><thead><tr><th>Teacher</th><th>Subject</th><th>School Year</th><th>Papers</th><th>Overall</th><th></th></tr></thead><tbody id="k2Rows"></tbody></table></div></div></div>'+pdfModal()+'</section>';}
    function switchTab(n){document.querySelectorAll('[data-k2tab]').forEach(function(b){b.classList.toggle('on',b.getAttribute('data-k2tab')===n);});document.querySelectorAll('.k2-panel').forEach(function(p){p.classList.remove('on');});var p=document.getElementById('k2Panel-'+n);if(p)p.classList.add('on');if(n==='saved')refresh();}
    function setCommon(){batch.teacher=String(batch.teacher||'').toUpperCase();document.getElementById('k2Teacher').value=batch.teacher;batch.subject=String(batch.subject||'').toUpperCase();document.getElementById('k2Subject').value=batch.subject;document.getElementById('k2SchoolYear').value=batch.schoolYear;}
    function drawBatch(){var h=document.getElementById('k2Batch');if(!h)return;syncCommon();var saved=!!batch.id&&!batch.dirty,n=batch.papers.length;h.innerHTML='<div><b>'+(batch.id?'Current saved batch':'Current unsaved batch')+'</b><span>'+n+' staged paper'+(n===1?'':'s')+(batch.dirty?' · Unsaved changes':saved?' · Ready for PDF/results':'')+'</span></div><div class="k2-batch-actions"><button id="k2SaveBatch" type="button"'+(!n?' disabled':'')+'>Save entire batch</button><button id="k2CompilePdf" type="button"'+(!saved?' disabled':'')+'>Preview compiled PDF</button><button id="k2BuildResults" type="button"'+(!saved?' disabled':'')+'>Build result template</button><button id="k2NewBatch" type="button">New batch</button></div>';document.getElementById('k2SaveBatch').onclick=saveEntireBatch;document.getElementById('k2CompilePdf').onclick=compilePdf;document.getElementById('k2BuildResults').onclick=buildResults;document.getElementById('k2NewBatch').onclick=newBatch;drawPaperChips();}
    function drawPaperChips(){var h=document.getElementById('k2PaperChips');if(!h)return;h.innerHTML=batch.papers.length?batch.papers.map(function(p,i){return '<div class="k2-paper-chip"><span><b>C.N. '+esc(p.classNo||'—')+' · '+esc(p.gradeLevel||'NO GRADE')+'</b>'+esc(p.student)+'</span><div><button data-paper-edit="'+i+'" type="button">Edit</button><button data-paper-remove="'+i+'" type="button">Remove</button></div></div>';}).join(''):'<div class="k2-paper-empty">No papers staged yet. Complete the paper below and add it to this batch.</div>';}
    function commonProblem(){syncCommon();if(!/^[^,]+,\s*[^,]+$/.test(batch.teacher))return 'Enter the teacher as SURNAME, FIRST NAME.';if(!batch.subject)return 'Enter the subject.';if(!/^\d+$/.test(batch.schoolYear))return 'School Year must contain numbers only.';return '';}
    function paperPayload(){return{classNo:document.getElementById('k2ClassNo').value.trim(),student:document.getElementById('k2Student').value.trim().toUpperCase(),gradeLevel:document.getElementById('k2GradeLevel').value,scores:scoreValues(),comment:document.getElementById('k2Comment').value.trim()};}
    function clearPaper(){editingPaper=-1;document.getElementById('k2ClassNo').value='';document.getElementById('k2Student').value='';document.getElementById('k2GradeLevel').value='';document.getElementById('k2Comment').value='';document.querySelectorAll('#k2Questions input').forEach(function(x){x.checked=false;});document.getElementById('k2AddPaper').textContent='Add paper to batch';drawResults();}
    function addPaper(){var p=paperPayload(),s=document.getElementById('k2Status');var problem=commonProblem();if(problem){s.textContent=problem;s.className='k2-status err';return;}if(p.classNo&&!/^\d+$/.test(p.classNo)){s.textContent='Class Number must be blank or contain digits only.';s.className='k2-status err';return;}if(!p.student){s.textContent='Enter the student name.';s.className='k2-status err';return;}if(['KINDER','GRADE 1','GRADE 2'].indexOf(p.gradeLevel)<0){s.textContent='Select Kinder, Grade 1, or Grade 2.';s.className='k2-status err';return;}if(p.scores.some(function(x){return x==null;})){s.textContent='Answer all 13 statements.';s.className='k2-status err';return;}if(editingPaper>=0)batch.papers[editingPaper]=p;else batch.papers.push(p);batch.dirty=true;saveDraft();s.textContent=(editingPaper>=0?'Paper updated.':'Paper added.')+' Save the entire batch when all papers are entered.';s.className='k2-status ok';clearPaper();drawBatch();}
    function editPaper(i){var p=batch.papers[i];if(!p)return;editingPaper=i;document.getElementById('k2ClassNo').value=p.classNo;document.getElementById('k2Student').value=p.student;document.getElementById('k2GradeLevel').value=p.gradeLevel||'';document.getElementById('k2Comment').value=p.comment||'';document.querySelectorAll('#k2Questions input').forEach(function(x){x.checked=false;});p.scores.forEach(function(v,j){var x=document.querySelector('input[name="k2q'+j+'"][value="'+v+'"]');if(x)x.checked=true;});document.getElementById('k2AddPaper').textContent='Update staged paper';drawResults();window.scrollTo({top:document.getElementById('k2Card').offsetTop,behavior:'smooth'});}
    function removePaper(i){if(!confirm('Remove this paper from the current batch?'))return;batch.papers.splice(i,1);batch.dirty=true;if(editingPaper===i)clearPaper();else if(editingPaper>i)editingPaper--;saveDraft();drawBatch();}
    function busy(on,text){['k2SaveBatch','k2CompilePdf','k2BuildResults'].forEach(function(id){var b=document.getElementById(id);if(b)b.disabled=on;});var s=document.getElementById('k2Status');if(s&&text){s.textContent=text;s.className='k2-status';}}
    function saveEntireBatch(){var s=document.getElementById('k2Status'),problem=commonProblem();if(problem){s.textContent=problem;s.className='k2-status err';return;}if(!batch.papers.length){s.textContent='Add at least one paper to the batch.';s.className='k2-status err';return;}busy(true,'Saving all papers as one batch record…');api.saveK2Batch({id:batch.id,teacher:batch.teacher,subject:batch.subject,schoolYear:batch.schoolYear,papers:batch.papers}).then(function(d){batch={id:d.id,teacher:d.teacher,subject:d.subject,schoolYear:d.schoolYear,papers:d.papers||batch.papers,dirty:false};saveDraft();drawBatch();s.textContent='Saved '+batch.papers.length+' paper(s) as one database batch record.';s.className='k2-status ok';toast('Entire batch saved as one record.','ok');loaded=false;}).catch(function(e){drawBatch();s.textContent=errText(e,'Batch save failed.');s.className='k2-status err';});}
    function newBatch(){if((batch.papers.length||batch.dirty)&&!confirm('Start a new batch? Save first if you want to keep unsaved changes.'))return;batch=blankBatch();setCommon();saveDraft();clearPaper();drawBatch();document.getElementById('k2Status').textContent='';}
    function filters(){return{teacher:document.getElementById('k2FilterTeacher').value.trim(),subject:document.getElementById('k2FilterSubject').value.trim(),schoolYear:document.getElementById('k2FilterYear').value.trim()};}
    function refresh(){var m=document.getElementById('k2ListMeta');if(m)m.textContent='Loading…';return api.listK2Batches(filters()).then(function(d){batches=(d&&d.batches)||[];loaded=true;drawRows(d&&d.total);}).catch(function(e){if(m)m.textContent=errText(e,'Could not load saved batches.');});}
    function drawRows(total){var b=document.getElementById('k2Rows'),m=document.getElementById('k2ListMeta');if(!b)return;if(m)m.textContent=(total==null?batches.length:total)+' saved batch record(s)';b.innerHTML=batches.length?batches.map(function(e){return '<tr><td>'+esc(e.teacher)+'</td><td>'+esc(e.subject)+'</td><td>'+esc(e.schoolYear)+'</td><td>'+esc(e.paperCount)+'</td><td><b>'+fmt(e.overallAvg)+'</b></td><td class="k2-row-actions"><button data-open="'+esc(e.id)+'">Open</button><button data-pdf="'+esc(e.id)+'">PDF</button><button data-results="'+esc(e.id)+'">Results</button><button class="danger" data-del="'+esc(e.id)+'">Delete</button></td></tr>';}).join(''):'<tr><td colspan="6" class="k2-empty">No saved batches match the filters.</td></tr>';}
    function openBatch(id){var e=batches.find(function(x){return x.id===id;});if(!e)return;if(batch.dirty&&!confirm('Open this saved batch and discard the current unsaved changes?'))return;batch={id:e.id,teacher:String(e.teacher||'').toUpperCase(),subject:String(e.subject||'').toUpperCase(),schoolYear:e.schoolYear,papers:(e.papers||[]).map(function(p){p.student=String(p.student||'').toUpperCase();p.gradeLevel=String(p.gradeLevel||'').toUpperCase();return p;}),dirty:false};setCommon();saveDraft();clearPaper();drawBatch();switchTab('entry');document.getElementById('k2Status').textContent='Saved batch opened. Edit staged papers, then save the entire batch to update its one database record.';}
    function bytesFrom(d){var raw=atob(d.base64),a=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a;}
    function showPdf(d){closePdf();var blob=new Blob([bytesFrom(d)],{type:'application/pdf'});previewUrl=URL.createObjectURL(blob);document.getElementById('k2PdfFrame').src=previewUrl;document.getElementById('k2PdfName').textContent=d.name;var drive=document.getElementById('k2PdfDrive');drive.href=d.driveUrl||'#';drive.style.display=d.driveUrl?'inline-flex':'none';document.getElementById('k2PdfDownload').onclick=function(){var a=document.createElement('a');a.href=previewUrl;a.download=d.name;document.body.appendChild(a);a.click();a.remove();};document.getElementById('k2PdfFoot').innerHTML='Saved in Google Drive: <a href="'+esc(d.folderUrl||d.driveUrl||'#')+'" target="_blank" rel="noopener">open folder</a>';document.getElementById('k2PdfModal').hidden=false;}
    function closePdf(){var m=document.getElementById('k2PdfModal');if(m)m.hidden=true;var f=document.getElementById('k2PdfFrame');if(f)f.src='about:blank';if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl='';}}
    function compilePdf(id){id=typeof id==='string'?id:batch.id;if(!id)return;toast('Compiling answered paper copies…');api.compileK2BatchPdf(id).then(function(d){showPdf(d);toast('One compiled PDF saved in Drive and ready to download.','ok');}).catch(function(e){toast(errText(e,'PDF compilation failed.'),'err');});}
    function buildResults(id){id=typeof id==='string'?id:batch.id;if(!id)return;var s=document.getElementById('k2Status');if(s){s.textContent='Building the Kinder–Grade 2 result template…';s.className='k2-status';}api.buildK2ManualResults(id).then(function(d){if(s){s.innerHTML='Result workbook created: <a href="'+esc(d.url)+'" target="_blank" rel="noopener">open '+esc(d.name)+'</a> · <a href="'+esc(d.xlsxUrl)+'">download Excel</a> · Tab: '+esc((d.tabs||[]).join(', '));s.className='k2-status ok';}toast('Subject-named result tab created.','ok');}).catch(function(e){if(s){s.textContent=errText(e,'Could not build the result template.');s.className='k2-status err';}else toast(errText(e,'Could not build results.'),'err');});}
    function removeBatch(id){if(!confirm('Delete this entire saved batch record?'))return;api.deleteK2Batch(id).then(function(){if(batch.id===id){batch=blankBatch();setCommon();saveDraft();clearPaper();drawBatch();}refresh();toast('Batch deleted.','ok');}).catch(function(e){toast(errText(e,'Delete failed.'),'err');});}
    function wire(){document.getElementById('k2Collapse').onclick=function(){var b=document.getElementById('k2Body'),o=b.hidden;b.hidden=!o;this.textContent=o?'Close encoder':'Open encoder';if(o&&!loaded)refresh();};document.querySelectorAll('[data-k2tab]').forEach(function(b){b.onclick=function(){switchTab(b.getAttribute('data-k2tab'));};});document.getElementById('k2Questions').addEventListener('change',drawResults);document.getElementById('k2ClassNo').addEventListener('input',function(){this.value=this.value.replace(/\D/g,'');});['k2Teacher','k2Student','k2Subject'].forEach(function(id){document.getElementById(id).addEventListener('input',function(){var a=this.selectionStart,b=this.selectionEnd;this.value=this.value.toUpperCase();try{this.setSelectionRange(a,b);}catch(e){}});});document.getElementById('k2SchoolYear').addEventListener('input',function(){this.value=this.value.replace(/\D/g,'');});['k2Teacher','k2Subject','k2SchoolYear'].forEach(function(id){document.getElementById(id).addEventListener('input',markDirty);});document.getElementById('k2AddPaper').onclick=addPaper;document.getElementById('k2ClearPaper').onclick=clearPaper;document.getElementById('k2Filter').onclick=refresh;document.getElementById('k2PaperChips').onclick=function(ev){var t=ev.target,i=t.getAttribute('data-paper-edit');if(i!==null)editPaper(Number(i));i=t.getAttribute('data-paper-remove');if(i!==null)removePaper(Number(i));};document.getElementById('k2Rows').onclick=function(ev){var t=ev.target,id=t.getAttribute('data-open')||t.getAttribute('data-pdf')||t.getAttribute('data-results')||t.getAttribute('data-del');if(!id)return;if(t.hasAttribute('data-open'))openBatch(id);else if(t.hasAttribute('data-pdf'))compilePdf(id);else if(t.hasAttribute('data-results'))buildResults(id);else removeBatch(id);};document.getElementById('k2PdfClose').onclick=closePdf;document.getElementById('k2PdfModal').onclick=function(e){if(e.target===this)closePdf();};setCommon();drawResults();drawBatch();}
    function mount(){var host=document.getElementById('k2Mount')||document.getElementById('ebMount')||document.getElementById('evalView');if(!host)return false;if(document.getElementById('k2Card'))return true;loadDraft();var w=document.createElement('div');w.innerHTML=template();host.appendChild(w.firstChild);wire();return true;}
    return{mount:mount,refresh:refresh};
})();
